#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import build_generic_battle_runtime_v1_candidate443_g07 as candidate443_builder

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "artifacts" / "generic-battle-runtime-v1-candidate446-g07"

_ALLOWED_CLIMAX_DIFFS = {
    ("type",),
    ("actors",),
    ("attackTarget",),
    ("tacticalPurpose",),
    ("physicsRequirements",),
    ("requiredOutcome",),
}


def _diff_paths(before: Any, after: Any, prefix: tuple[str, ...] = ()) -> set[tuple[str, ...]]:
    if type(before) is not type(after):
        return {prefix}
    if isinstance(before, dict):
        out: set[tuple[str, ...]] = set()
        for key in set(before) | set(after):
            if key not in before or key not in after:
                out.add(prefix + (str(key),))
            else:
                out |= _diff_paths(before[key], after[key], prefix + (str(key),))
        return out
    if isinstance(before, list):
        return set() if before == after else {prefix}
    return set() if before == after else {prefix}


def _diffs_within_climax_scope(diffs: set[tuple[str, ...]]) -> bool:
    # _diff_paths reports nested leaf paths when a whole allowed object is
    # replaced (for example physicsRequirements.minQualifiedContacts). The G07
    # scope contract is defined by the allowed top-level climax fields, so child
    # paths are valid only when their top-level field is explicitly allowlisted.
    return bool(diffs) and all(
        bool(path) and (path[0],) in _ALLOWED_CLIMAX_DIFFS
        for path in diffs
    )


def _patch_climax(request: dict[str, Any]) -> dict[str, Any]:
    events = {str(row.get("eventId")): row for row in request["battlePlan"]["events"]}
    climax = events["evt-climax"]
    before = json.loads(json.dumps(climax))
    climax.update({
        "type": "CAUSAL_CLIMAX_STATE",
        "actors": ["actor_alpha", "actor_beta"],
        "attackTarget": "",
        "tacticalPurpose": "RESOLVE_REVERSAL",
        "physicsRequirements": {},
        "requiredOutcome": (
            "The climax is causally earned from the already-realized physical reversal and persistent battle state. "
            "It does not require or prescribe a new collision."
        ),
    })
    diffs = _diff_paths(before, climax)
    if not _diffs_within_climax_scope(diffs):
        raise RuntimeError(f"CANDIDATE446_CLIMAX_DIFF_SCOPE_INVALID:{sorted(diffs)}")
    return before


def _verify(path: Path, before_climax: dict[str, Any]) -> None:
    request = json.loads(path.read_text(encoding="utf-8"))
    events = {str(row.get("eventId")): row for row in request["battlePlan"]["events"]}
    climax = events["evt-climax"]
    if str(climax.get("attackTarget") or ""):
        raise RuntimeError("CANDIDATE446_CLIMAX_MUST_NOT_TARGET_NEW_CONTACT")
    if climax.get("actors") != ["actor_alpha", "actor_beta"]:
        raise RuntimeError("CANDIDATE446_CLIMAX_MUST_REPRESENT_BATTLE_STATE")
    if climax.get("physicsRequirements") not in ({}, None):
        raise RuntimeError("CANDIDATE446_CLIMAX_PHYSICS_REQUIREMENTS_FORBIDDEN")
    if bool((climax.get("damage") or {}).get("required")):
        raise RuntimeError("CANDIDATE446_CLIMAX_DAMAGE_REQUIREMENT_FORBIDDEN")
    if climax.get("causedByEventIds") != ["evt-counterattack"]:
        raise RuntimeError("CANDIDATE446_CLIMAX_CAUSAL_DEPENDENCY_DRIFT")

    # Escalation and counterattack remain exactly the physical actor-only intent
    # generated by Candidate 4.4.3. No collision mechanics are added or changed.
    for event_id in ("evt-escalation", "evt-counterattack"):
        event = events[event_id]
        target = str(event.get("attackTarget") or "")
        if not target or ":" in target:
            raise RuntimeError(f"CANDIDATE446_PHYSICAL_EVENT_NOT_ACTOR_ONLY:{event_id}:{target}")
        req = event.get("physicsRequirements") or {}
        if set(req) != {"minQualifiedContacts", "minDistinctAttackers"}:
            raise RuntimeError(f"CANDIDATE446_PHYSICAL_EVENT_CONTRACT_DRIFT:{event_id}:{sorted(req)}")

    diffs = _diff_paths(before_climax, climax)
    if not _diffs_within_climax_scope(diffs):
        raise RuntimeError(f"CANDIDATE446_POSTWRITE_DIFF_SCOPE_INVALID:{sorted(diffs)}")

    raw = json.dumps(request, sort_keys=True).lower()
    for forbidden in (
        "collisionframe", "contactframe", "impactframe", "targetenergyj", "impactenergyj",
        "targetimpactspeedmps", "trajectorypoints", "pathpoints", "waypoints",
        "positionkeyframes", "velocitykeyframes", "steeringangle", "brakingpoint",
        "approachvector", "collisionpoint", "contactpoint", "forcedwinner", "winnerid",
    ):
        if forbidden in raw:
            raise RuntimeError(f"CANDIDATE446_FORBIDDEN_STORY_COLLISION_CHOREOGRAPHY:{forbidden}")


def main() -> None:
    candidate443_builder.OUT = OUT
    candidate443_builder.main()

    fixture_rows: list[dict[str, Any]] = []
    for name in ("exact-bugatti", "generic-hypercar"):
        path = OUT / name / "request.json"
        request = json.loads(path.read_text(encoding="utf-8"))
        before = _patch_climax(request)
        path.write_text(json.dumps(request, indent=2, sort_keys=True), encoding="utf-8")
        _verify(path, before)
        fixture_rows.append({
            "name": name,
            "climaxRequiresContact": False,
            "climaxCausedBy": ["evt-counterattack"],
            "physicalEventsUnchanged": ["evt-escalation", "evt-counterattack"],
        })

    print(json.dumps({
        "marker": "GENERIC_BATTLE_RUNTIME_CANDIDATE446_G07_FIXTURES_PASS",
        "status": "PASS",
        "fixtureSemanticsChangedFromCandidate443": "CLIMAX_STATE_ONLY",
        "sameIntentStructureAcrossAssets": True,
        "storyIntentOnly": True,
        "storyTargetActorOnlyForPhysicalEvents": True,
        "storyTargetZonePrescribed": False,
        "runtimeSelectsSemanticEngagementSurfaceForPhysicalEvents": True,
        "climaxRealization": "CAUSAL_STATE_BEAT_FROM_REALIZED_REVERSAL",
        "climaxRequiresNewContact": False,
        "climaxPrescribesPhysics": False,
        "damageRequiredForG07": False,
        "speedIntentPrescribed": False,
        "exactCollisionFrameTarget": False,
        "exactImpactEnergyTarget": False,
        "manualTrajectoryPoints": False,
        "forcedWinner": False,
        "perAssetCollisionEngineering": False,
        "issR041ScopePreserved": True,
        "issR042ScopePreserved": True,
        "issR043ScopePreflightPreserved": True,
        "issR044UserPostflightApprovalRequired": True,
        "fixtures": fixture_rows,
    }, sort_keys=True))


if __name__ == "__main__":
    main()
